// GENERATED by scripts/build-messier-catalog.mjs — do not edit by hand; re-run to refresh.
// Data: OpenNGC (github.com/mattiaverga/OpenNGC) NGC.csv + addendum.csv, CC-BY-SA-4.0.
// Attribution is REQUIRED wherever this data surfaces (TargetPanel prints "OPENNGC" per DSO).
// M102 carries OpenNGC's contested-id stance (type Dup) — the panel says so instead of picking.

/** One Messier object — J2000, magnitudes/type/size verbatim from OpenNGC. */
export interface MessierEntry {
  /** Messier number 1–110. */
  m: number;
  /** Primary NGC/IC designation, if the object has one. */
  ngc: string | null;
  /** Common names ("Andromeda Galaxy", …). */
  names: string[];
  /** OpenNGC type code (G, OCl, GCl, PN, SNR, …). */
  dsoType: string;
  kind: "galaxy" | "nebula" | "cluster" | "star" | "other";
  typeLabel: string;
  raDeg: number;
  decDeg: number;
  /** V magnitude (B where V is missing) — null when OpenNGC has neither. */
  vmag: number | null;
  majArcmin: number | null;
  minArcmin: number | null;
  paDeg: number | null;
  constellation: string | null;
}

export const MESSIER: MessierEntry[] = [
  {m: 1,ngc: "NGC 1952",names: ["Crab Nebula"],dsoType: "SNR",kind: "nebula",typeLabel: "SUPERNOVA REMNANT",raDeg: 83.63321,decDeg: 22.01447,vmag: 8.4,majArcmin: 8,minArcmin: 4,paDeg: null,constellation: "Tau"},
  {m: 2,ngc: "NGC 7089",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 323.36254,decDeg: -0.82331,vmag: 6.25,majArcmin: 8.4,minArcmin: null,paDeg: null,constellation: "Aqr"},
  {m: 3,ngc: "NGC 5272",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 205.54679,decDeg: 28.37544,vmag: 6.39,majArcmin: 16.2,minArcmin: null,paDeg: null,constellation: "CVn"},
  {m: 4,ngc: "NGC 6121",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 245.8975,decDeg: -26.52553,vmag: 5.4,majArcmin: 28.2,minArcmin: null,paDeg: null,constellation: "Sco"},
  {m: 5,ngc: "NGC 5904",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 229.64063,decDeg: 2.08269,vmag: 5.95,majArcmin: 15,minArcmin: null,paDeg: null,constellation: "Se1"},
  {m: 6,ngc: "NGC 6405",names: ["Butterfly Cluster"],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 265.08646,decDeg: -32.25417,vmag: 4.2,majArcmin: 15.6,minArcmin: null,paDeg: null,constellation: "Sco"},
  {m: 7,ngc: "NGC 6475",names: ["Ptolemy's Cluster"],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 268.46325,decDeg: -34.79283,vmag: 3.3,majArcmin: 22.2,minArcmin: null,paDeg: null,constellation: "Sco"},
  {m: 8,ngc: "NGC 6523",names: ["Lagoon Nebula"],dsoType: "Neb",kind: "nebula",typeLabel: "NEBULA",raDeg: 270.92196,decDeg: -24.38017,vmag: 5.8,majArcmin: 45,minArcmin: 30,paDeg: null,constellation: "Sgr"},
  {m: 9,ngc: "NGC 6333",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 259.79908,decDeg: -18.51625,vmag: 8.42,majArcmin: 6.9,minArcmin: null,paDeg: null,constellation: "Oph"},
  {m: 10,ngc: "NGC 6254",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 254.28746,decDeg: -4.09933,vmag: 4.98,majArcmin: 9.3,minArcmin: null,paDeg: null,constellation: "Oph"},
  {m: 11,ngc: "NGC 6705",names: ["Amas de l'Ecu de Sobieski","Wild Duck Cluster"],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 282.77496,decDeg: -6.27003,vmag: 5.8,majArcmin: 9,minArcmin: null,paDeg: null,constellation: "Sct"},
  {m: 12,ngc: "NGC 6218",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 251.8105,decDeg: -1.94783,vmag: 6.07,majArcmin: 11.1,minArcmin: null,paDeg: null,constellation: "Oph"},
  {m: 13,ngc: "NGC 6205",names: ["Hercules Globular Cluster"],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 250.42346,decDeg: 36.46131,vmag: 5.8,majArcmin: 16.5,minArcmin: null,paDeg: null,constellation: "Her"},
  {m: 14,ngc: "NGC 6402",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 264.40067,decDeg: -3.24592,vmag: 5.73,majArcmin: 9.9,minArcmin: null,paDeg: null,constellation: "Oph"},
  {m: 15,ngc: "NGC 7078",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 322.49325,decDeg: 12.16683,vmag: 6.3,majArcmin: 11.1,minArcmin: null,paDeg: null,constellation: "Peg"},
  {m: 16,ngc: "NGC 6611",names: ["Eagle Nebula"],dsoType: "Neb",kind: "nebula",typeLabel: "NEBULA",raDeg: 274.70071,decDeg: -13.80722,vmag: 6,majArcmin: 120,minArcmin: 25,paDeg: null,constellation: "Se2"},
  {m: 17,ngc: "NGC 6618",names: ["Checkmark Nebula","Lobster Nebula","Swan Nebula","omega Nebula"],dsoType: "Neb",kind: "nebula",typeLabel: "NEBULA",raDeg: 275.19629,decDeg: -16.17153,vmag: 7,majArcmin: 12.6,minArcmin: null,paDeg: null,constellation: "Sgr"},
  {m: 18,ngc: "NGC 6613",names: [],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 274.99371,decDeg: -17.10197,vmag: 6.9,majArcmin: 6,minArcmin: null,paDeg: null,constellation: "Sgr"},
  {m: 19,ngc: "NGC 6273",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 255.657,decDeg: -26.26794,vmag: 5.57,majArcmin: 7.5,minArcmin: null,paDeg: null,constellation: "Oph"},
  {m: 20,ngc: "NGC 6514",names: ["Trifid Nebula"],dsoType: "Neb",kind: "nebula",typeLabel: "NEBULA",raDeg: 270.67546,decDeg: -22.97189,vmag: 8.5,majArcmin: 28,minArcmin: 28,paDeg: null,constellation: "Sgr"},
  {m: 21,ngc: "NGC 6531",names: [],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 271.05604,decDeg: -22.49006,vmag: 5.9,majArcmin: 6,minArcmin: null,paDeg: null,constellation: "Sgr"},
  {m: 22,ngc: "NGC 6656",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 279.10083,decDeg: -23.90342,vmag: 6.17,majArcmin: 12.6,minArcmin: null,paDeg: null,constellation: "Sgr"},
  {m: 23,ngc: "NGC 6494",names: [],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 269.26988,decDeg: -18.98533,vmag: 5.5,majArcmin: 16.8,minArcmin: null,paDeg: null,constellation: "Sgr"},
  {m: 24,ngc: "IC 4715",names: ["Small Sgr Star Cloud"],dsoType: "*Ass",kind: "cluster",typeLabel: "STELLAR ASSOCIATION",raDeg: 274.23383,decDeg: -18.51456,vmag: 4.5,majArcmin: 120,minArcmin: 60,paDeg: 90,constellation: "Sgr"},
  {m: 25,ngc: "IC 4725",names: [],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 277.94488,decDeg: -19.11494,vmag: 4.6,majArcmin: 14.1,minArcmin: null,paDeg: null,constellation: "Sgr"},
  {m: 26,ngc: "NGC 6694",names: [],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 281.32775,decDeg: -9.38361,vmag: 8.87,majArcmin: 6,minArcmin: null,paDeg: null,constellation: "Sct"},
  {m: 27,ngc: "NGC 6853",names: ["Dumbbell Nebula"],dsoType: "PN",kind: "nebula",typeLabel: "PLANETARY NEBULA",raDeg: 299.90158,decDeg: 22.72103,vmag: 7.4,majArcmin: 6.7,minArcmin: null,paDeg: null,constellation: "Vul"},
  {m: 28,ngc: "NGC 6626",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 276.13704,decDeg: -24.86983,vmag: 6.9,majArcmin: 5.1,minArcmin: null,paDeg: null,constellation: "Sgr"},
  {m: 29,ngc: "NGC 6913",names: [],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 305.99071,decDeg: 38.50767,vmag: 6.6,majArcmin: 3.6,minArcmin: null,paDeg: null,constellation: "Cyg"},
  {m: 30,ngc: "NGC 7099",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 325.09175,decDeg: -23.17908,vmag: 7.1,majArcmin: 9,minArcmin: null,paDeg: null,constellation: "Cap"},
  {m: 31,ngc: "NGC 224",names: ["Andromeda Galaxy"],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 10.68479,decDeg: 41.26906,vmag: 3.44,majArcmin: 177.83,minArcmin: 69.66,paDeg: 35,constellation: "And"},
  {m: 32,ngc: "NGC 221",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 10.67429,decDeg: 40.86528,vmag: 8.13,majArcmin: 7.74,minArcmin: 4.86,paDeg: 170,constellation: "And"},
  {m: 33,ngc: "NGC 598",names: ["Triangulum Galaxy","Triangulum Pinwheel"],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 23.46204,decDeg: 30.66022,vmag: 5.79,majArcmin: 62.09,minArcmin: 36.73,paDeg: 23,constellation: "Tri"},
  {m: 34,ngc: "NGC 1039",names: [],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 40.53083,decDeg: 42.74614,vmag: 5.2,majArcmin: 22.5,minArcmin: null,paDeg: null,constellation: "Per"},
  {m: 35,ngc: "NGC 2168",names: [],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 92.27108,decDeg: 24.33864,vmag: 5.1,majArcmin: 24,minArcmin: null,paDeg: null,constellation: "Gem"},
  {m: 36,ngc: "NGC 1960",names: [],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 84.07392,decDeg: 34.14075,vmag: 6,majArcmin: 7.2,minArcmin: null,paDeg: null,constellation: "Aur"},
  {m: 37,ngc: "NGC 2099",names: [],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 88.07646,decDeg: 32.553,vmag: 5.6,majArcmin: 11.4,minArcmin: null,paDeg: null,constellation: "Aur"},
  {m: 38,ngc: "NGC 1912",names: [],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 82.17704,decDeg: 35.85492,vmag: 6.4,majArcmin: 9.6,minArcmin: null,paDeg: null,constellation: "Aur"},
  {m: 39,ngc: "NGC 7092",names: [],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 322.95133,decDeg: 48.43817,vmag: 4.6,majArcmin: 19.5,minArcmin: null,paDeg: null,constellation: "Cyg"},
  {m: 40,ngc: null,names: [],dsoType: "**",kind: "star",typeLabel: "DOUBLE STAR",raDeg: 185.56708,decDeg: 58.08444,vmag: 8,majArcmin: null,minArcmin: null,paDeg: null,constellation: "UMa"},
  {m: 41,ngc: "NGC 2287",names: [],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 101.49975,decDeg: -20.75422,vmag: 4.5,majArcmin: 12,minArcmin: null,paDeg: null,constellation: "CMa"},
  {m: 42,ngc: "NGC 1976",names: ["Great Orion Nebula","Orion Nebula"],dsoType: "Cl+N",kind: "nebula",typeLabel: "CLUSTER + NEBULA",raDeg: 83.81867,decDeg: -5.38967,vmag: 4,majArcmin: 90,minArcmin: 60,paDeg: null,constellation: "Ori"},
  {m: 43,ngc: "NGC 1982",names: ["Mairan's Nebula"],dsoType: "HII",kind: "nebula",typeLabel: "H II REGION",raDeg: 83.88075,decDeg: -5.26747,vmag: 9,majArcmin: 20,minArcmin: 15,paDeg: null,constellation: "Ori"},
  {m: 44,ngc: "NGC 2632",names: ["Beehive","Praesepe Cluster"],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 130.0925,decDeg: 19.67206,vmag: 3.1,majArcmin: 108.6,minArcmin: null,paDeg: null,constellation: "Cnc"},
  {m: 45,ngc: null,names: ["Pleiades"],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 56.86917,decDeg: 24.10528,vmag: 1.2,majArcmin: 150,minArcmin: 150,paDeg: 90,constellation: "Tau"},
  {m: 46,ngc: "NGC 2437",names: [],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 115.44508,decDeg: -14.81,vmag: 6.1,majArcmin: 21,minArcmin: null,paDeg: null,constellation: "Pup"},
  {m: 47,ngc: "NGC 2422",names: [],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 114.14592,decDeg: -14.48261,vmag: 4.4,majArcmin: 19.8,minArcmin: null,paDeg: null,constellation: "Pup"},
  {m: 48,ngc: "NGC 2548",names: [],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 123.42992,decDeg: -5.75044,vmag: 5.8,majArcmin: 28.2,minArcmin: null,paDeg: null,constellation: "Hya"},
  {m: 49,ngc: "NGC 4472",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 187.44483,decDeg: 8.00047,vmag: 8.28,majArcmin: 10.21,minArcmin: 8.38,paDeg: 156,constellation: "Vir"},
  {m: 50,ngc: "NGC 2323",names: [],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 105.66863,decDeg: -8.36403,vmag: 5.9,majArcmin: 14.1,minArcmin: null,paDeg: null,constellation: "Mon"},
  {m: 51,ngc: "NGC 5194",names: ["Whirlpool Galaxy"],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 202.46962,decDeg: 47.19517,vmag: 8.36,majArcmin: 13.71,minArcmin: 11.67,paDeg: 163,constellation: "CVn"},
  {m: 52,ngc: "NGC 7654",names: [],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 351.20167,decDeg: 61.59317,vmag: 6.9,majArcmin: 9.9,minArcmin: null,paDeg: null,constellation: "Cas"},
  {m: 53,ngc: "NGC 5024",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 198.23012,decDeg: 18.16911,vmag: 7.79,majArcmin: 9,minArcmin: null,paDeg: null,constellation: "Com"},
  {m: 54,ngc: "NGC 6715",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 283.76363,decDeg: -30.4785,vmag: 7.7,majArcmin: 5.1,minArcmin: null,paDeg: null,constellation: "Sgr"},
  {m: 55,ngc: "NGC 6809",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 294.9975,decDeg: -30.96208,vmag: 6.49,majArcmin: 12,minArcmin: null,paDeg: null,constellation: "Sgr"},
  {m: 56,ngc: "NGC 6779",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 289.14796,decDeg: 30.1845,vmag: 8.4,majArcmin: 5.8,minArcmin: null,paDeg: null,constellation: "Lyr"},
  {m: 57,ngc: "NGC 6720",names: ["Ring Nebula"],dsoType: "PN",kind: "nebula",typeLabel: "PLANETARY NEBULA",raDeg: 283.39587,decDeg: 33.02858,vmag: 8.8,majArcmin: 1.27,minArcmin: null,paDeg: null,constellation: "Lyr"},
  {m: 58,ngc: "NGC 4579",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 189.43133,decDeg: 11.81819,vmag: 10.3,majArcmin: 5.01,minArcmin: 3.84,paDeg: 90,constellation: "Vir"},
  {m: 59,ngc: "NGC 4621",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 190.50933,decDeg: 11.64703,vmag: 9.56,majArcmin: 4.55,minArcmin: 3.21,paDeg: 165,constellation: "Vir"},
  {m: 60,ngc: "NGC 4649",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 190.91658,decDeg: 11.55269,vmag: 8.79,majArcmin: 6.78,minArcmin: 5.45,paDeg: 105,constellation: "Vir"},
  {m: 61,ngc: "NGC 4303",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 185.47875,decDeg: 4.47364,vmag: 10.25,majArcmin: 6.89,minArcmin: 6.56,paDeg: 20,constellation: "Vir"},
  {m: 62,ngc: "NGC 6266",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 255.3025,decDeg: -30.11236,vmag: 7.39,majArcmin: 7.8,minArcmin: null,paDeg: null,constellation: "Oph"},
  {m: 63,ngc: "NGC 5055",names: ["Sunflower Galaxy"],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 198.95554,decDeg: 42.02928,vmag: 8.61,majArcmin: 11.83,minArcmin: 7.16,paDeg: 103,constellation: "CVn"},
  {m: 64,ngc: "NGC 4826",names: ["Black Eye Galaxy","Evil Eye Galaxy"],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 194.18183,decDeg: 21.68297,vmag: 8.52,majArcmin: 10.52,minArcmin: 5.33,paDeg: 114,constellation: "Com"},
  {m: 65,ngc: "NGC 3623",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 169.733,decDeg: 13.09236,vmag: 9.32,majArcmin: 7.64,minArcmin: 1.97,paDeg: 173,constellation: "Leo"},
  {m: 66,ngc: "NGC 3627",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 170.06233,decDeg: 12.99153,vmag: 8.92,majArcmin: 10.28,minArcmin: 4.61,paDeg: 168,constellation: "Leo"},
  {m: 67,ngc: "NGC 2682",names: [],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 132.83388,decDeg: 11.81194,vmag: 6.9,majArcmin: 33,minArcmin: null,paDeg: null,constellation: "Cnc"},
  {m: 68,ngc: "NGC 4590",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 189.86671,decDeg: -26.74303,vmag: 7.96,majArcmin: 6.6,minArcmin: null,paDeg: null,constellation: "Hya"},
  {m: 69,ngc: "NGC 6637",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 277.84679,decDeg: -32.34797,vmag: 8.31,majArcmin: 5.7,minArcmin: null,paDeg: null,constellation: "Sgr"},
  {m: 70,ngc: "NGC 6681",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 280.80267,decDeg: -32.29189,vmag: 9.06,majArcmin: 6.6,minArcmin: null,paDeg: null,constellation: "Sgr"},
  {m: 71,ngc: "NGC 6838",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 298.44212,decDeg: 18.77839,vmag: 6.1,majArcmin: 6.9,minArcmin: null,paDeg: null,constellation: "Sge"},
  {m: 72,ngc: "NGC 6981",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 313.36629,decDeg: -12.53706,vmag: 8.96,majArcmin: 4.5,minArcmin: null,paDeg: null,constellation: "Aqr"},
  {m: 73,ngc: "NGC 6994",names: [],dsoType: "Other",kind: "other",typeLabel: "OBJECT",raDeg: 314.73321,decDeg: -12.6355,vmag: 8.9,majArcmin: null,minArcmin: null,paDeg: null,constellation: "Aqr"},
  {m: 74,ngc: "NGC 628",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 24.17396,decDeg: 15.78367,vmag: 9.31,majArcmin: 9.89,minArcmin: 9.33,paDeg: 87,constellation: "Psc"},
  {m: 75,ngc: "NGC 6864",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 301.52017,decDeg: -21.92222,vmag: 8.26,majArcmin: 3.6,minArcmin: null,paDeg: null,constellation: "Sgr"},
  {m: 76,ngc: "NGC 650",names: ["Barbell Nebula","Cork Nebula","Little Dumbbell Nebula"],dsoType: "PN",kind: "nebula",typeLabel: "PLANETARY NEBULA",raDeg: 25.58204,decDeg: 51.57547,vmag: 10.1,majArcmin: 1.12,minArcmin: null,paDeg: null,constellation: "Per"},
  {m: 77,ngc: "NGC 1068",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 40.66963,decDeg: -0.01328,vmag: 9.29,majArcmin: 6.11,minArcmin: 5.61,paDeg: 12,constellation: "Cet"},
  {m: 78,ngc: "NGC 2068",names: [],dsoType: "RfN",kind: "nebula",typeLabel: "REFLECTION NEBULA",raDeg: 86.69092,decDeg: 0.07931,vmag: 8,majArcmin: 4.5,minArcmin: null,paDeg: null,constellation: "Ori"},
  {m: 79,ngc: "NGC 1904",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 81.04413,decDeg: -24.52422,vmag: 8.16,majArcmin: 7.2,minArcmin: null,paDeg: null,constellation: "Lep"},
  {m: 80,ngc: "NGC 6093",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 244.26046,decDeg: -22.97511,vmag: 7.3,majArcmin: 5.7,minArcmin: null,paDeg: null,constellation: "Sco"},
  {m: 81,ngc: "NGC 3031",names: ["Bode's Galaxy"],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 148.88821,decDeg: 69.06531,vmag: 6.92,majArcmin: 21.63,minArcmin: 11.25,paDeg: 157,constellation: "UMa"},
  {m: 82,ngc: "NGC 3034",names: ["Cigar Galaxy"],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 148.96971,decDeg: 69.67939,vmag: 8.3,majArcmin: 10.99,minArcmin: 5.11,paDeg: 66,constellation: "UMa"},
  {m: 83,ngc: "NGC 5236",names: ["Southern Pinwheel Galaxy"],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 204.25396,decDeg: -29.86542,vmag: 7.21,majArcmin: 13.61,minArcmin: 13.21,paDeg: 45,constellation: "Hya"},
  {m: 84,ngc: "NGC 4374",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 186.26558,decDeg: 12.88697,vmag: 9.79,majArcmin: 7.41,minArcmin: 6.44,paDeg: 133,constellation: "Vir"},
  {m: 85,ngc: "NGC 4382",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 186.35046,decDeg: 18.1915,vmag: 9.05,majArcmin: 6.95,minArcmin: 5.35,paDeg: 12,constellation: "Com"},
  {m: 86,ngc: "NGC 4406",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 186.54892,decDeg: 12.94622,vmag: 8.86,majArcmin: 11.53,minArcmin: 8.43,paDeg: 128,constellation: "Vir"},
  {m: 87,ngc: "NGC 4486",names: ["Virgo Galaxy"],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 187.70592,decDeg: 12.39111,vmag: 9,majArcmin: 7.11,minArcmin: 6.67,paDeg: 153,constellation: "Vir"},
  {m: 88,ngc: "NGC 4501",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 187.9965,decDeg: 14.42039,vmag: 10.33,majArcmin: 8.65,minArcmin: 4.38,paDeg: 138,constellation: "Com"},
  {m: 89,ngc: "NGC 4552",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 188.91587,decDeg: 12.55633,vmag: 10.08,majArcmin: 8.13,minArcmin: 8,paDeg: 150,constellation: "Vir"},
  {m: 90,ngc: "NGC 4569",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 189.20746,decDeg: 13.16294,vmag: 9.54,majArcmin: 9.12,minArcmin: 3.82,paDeg: 22,constellation: "Vir"},
  {m: 91,ngc: "NGC 4548",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 188.86021,decDeg: 14.49633,vmag: 10.96,majArcmin: 5.55,minArcmin: 4.52,paDeg: 150,constellation: "Com"},
  {m: 92,ngc: "NGC 6341",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 259.28029,decDeg: 43.13653,vmag: 6.52,majArcmin: 14.4,minArcmin: null,paDeg: null,constellation: "Her"},
  {m: 93,ngc: "NGC 2447",names: [],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 116.12179,decDeg: -23.85308,vmag: 6.2,majArcmin: 15,minArcmin: null,paDeg: null,constellation: "Pup"},
  {m: 94,ngc: "NGC 4736",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 192.72108,decDeg: 41.12044,vmag: 8.24,majArcmin: 7.74,minArcmin: 6.68,paDeg: 105,constellation: "CVn"},
  {m: 95,ngc: "NGC 3351",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 160.99042,decDeg: 11.70381,vmag: 9.77,majArcmin: 7.23,minArcmin: 4.45,paDeg: 11,constellation: "Leo"},
  {m: 96,ngc: "NGC 3368",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 161.69058,decDeg: 11.81994,vmag: 9.21,majArcmin: 8.26,minArcmin: 5.51,paDeg: 5,constellation: "Leo"},
  {m: 97,ngc: "NGC 3587",names: ["Owl Nebula"],dsoType: "PN",kind: "nebula",typeLabel: "PLANETARY NEBULA",raDeg: 168.69879,decDeg: 55.01903,vmag: 9.9,majArcmin: 3.58,minArcmin: null,paDeg: null,constellation: "UMa"},
  {m: 98,ngc: "NGC 4192",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 183.45121,decDeg: 14.90033,vmag: 10.84,majArcmin: 11.04,minArcmin: 2.66,paDeg: 152,constellation: "Com"},
  {m: 99,ngc: "NGC 4254",names: ["Coma Pinwheel","Virgo Cluster Pinwheel"],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 184.70667,decDeg: 14.4165,vmag: 9.84,majArcmin: 5.04,minArcmin: 4.74,paDeg: 23,constellation: "Com"},
  {m: 100,ngc: "NGC 4321",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 185.72846,decDeg: 15.82181,vmag: 9.47,majArcmin: 6.1,minArcmin: 5.62,paDeg: 108,constellation: "Com"},
  {m: 101,ngc: "NGC 5457",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 210.80225,decDeg: 54.34894,vmag: 7.9,majArcmin: 23.99,minArcmin: 23.07,paDeg: 28,constellation: "UMa"},
  {m: 102,ngc: null,names: [],dsoType: "Dup",kind: "other",typeLabel: "CONTESTED ID (SEE NOTES)",raDeg: 210.80225,decDeg: 54.34894,vmag: null,majArcmin: null,minArcmin: null,paDeg: null,constellation: "UMa"},
  {m: 103,ngc: "NGC 581",names: [],dsoType: "OCl",kind: "cluster",typeLabel: "OPEN CLUSTER",raDeg: 23.34088,decDeg: 60.658,vmag: 7.4,majArcmin: 4.5,minArcmin: null,paDeg: null,constellation: "Cas"},
  {m: 104,ngc: "NGC 4594",names: ["Sombrero Galaxy"],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 189.99762,decDeg: -11.62306,vmag: 8.59,majArcmin: 8.45,minArcmin: 4.91,paDeg: 90,constellation: "Vir"},
  {m: 105,ngc: "NGC 3379",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 161.95663,decDeg: 12.58161,vmag: 9.27,majArcmin: 4.89,minArcmin: 4.25,paDeg: 71,constellation: "Leo"},
  {m: 106,ngc: "NGC 4258",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 184.73958,decDeg: 47.30397,vmag: 9.29,majArcmin: 16.98,minArcmin: 7.24,paDeg: 150,constellation: "CVn"},
  {m: 107,ngc: "NGC 6171",names: [],dsoType: "GCl",kind: "cluster",typeLabel: "GLOBULAR CLUSTER",raDeg: 248.133,decDeg: -13.05364,vmag: 8.85,majArcmin: 7.8,minArcmin: null,paDeg: null,constellation: "Oph"},
  {m: 108,ngc: "NGC 3556",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 167.87904,decDeg: 55.67411,vmag: 10.05,majArcmin: 3.98,minArcmin: 1.66,paDeg: 79,constellation: "UMa"},
  {m: 109,ngc: "NGC 3992",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 179.39992,decDeg: 53.37453,vmag: 9.88,majArcmin: 8.07,minArcmin: 5.64,paDeg: 78,constellation: "UMa"},
  {m: 110,ngc: "NGC 205",names: [],dsoType: "G",kind: "galaxy",typeLabel: "GALAXY",raDeg: 10.092,decDeg: 41.68531,vmag: 8.15,majArcmin: 16.22,minArcmin: 9.59,paDeg: 170,constellation: "And"},
];
